# Generated by Django 4.0.4 on 2022-06-27 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glucoza', models.CharField(max_length=255, verbose_name='Уровень глюкозы')),
                ('he', models.FloatField(blank=True, verbose_name='Хлебные единицы')),
                ('insulin', models.FloatField(verbose_name='Количество инсулина')),
                ('food', models.TextField(blank=True, verbose_name='Употребляемая еда')),
                ('date_food', models.DateField(verbose_name='Дата приема пищи')),
                ('time_food', models.TimeField(verbose_name='Время приема пищи')),
                ('datatime_inbase', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('food_intake', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='diary_pages.fintake', verbose_name='Прием пищи')),
            ],
            options={
                'verbose_name': 'Дневник',
                'verbose_name_plural': 'Дневники',
            },
        ),
    ]
