# Generated by Django 4.0.4 on 2022-06-27 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary_pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diary',
            options={'verbose_name': 'Запись', 'verbose_name_plural': 'Записи'},
        ),
    ]
