# Generated by Django 4.0.4 on 2022-06-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary_pages', '0002_alter_diary_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diary',
            options={'verbose_name': 'Запись', 'verbose_name_plural': 'Записи'},
        ),
        migrations.AddField(
            model_name='diary',
            name='dia_user',
            field=models.CharField(default=1, max_length=255, verbose_name='Пользователь'),
            preserve_default=False,
        ),
    ]
