# Generated by Django 4.0.4 on 2022-07-02 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diary_pages', '0003_alter_diary_options_diary_dia_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='dia_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='glucoza',
            field=models.FloatField(max_length=255, verbose_name='Уровень глюкозы'),
        ),
    ]
