# Generated by Django 4.0.4 on 2022-07-02 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diary_pages', '0004_alter_diary_dia_user_alter_diary_glucoza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='dia_user',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
